name: Test & build master

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 10x-cards

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 10x-cards/.nvmrc
          cache: 'npm'
          cache-dependency-path: 10x-cards/package-lock.json

      - name: Install dependencies
        working-directory: ./10x-cards
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 10x-cards

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 10x-cards/.nvmrc
          cache: 'npm'
          cache-dependency-path: 10x-cards/package-lock.json

      - name: Install dependencies
        working-directory: ./10x-cards
        run: npm ci

      - name: Run ESLint
        working-directory: ./10x-cards
        run: npm run lint

      - name: Run Prettier
        working-directory: ./10x-cards
        run: npm run format

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 10x-cards

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 10x-cards/.nvmrc
          cache: 'npm'
          cache-dependency-path: 10x-cards/package-lock.json

      - name: Install dependencies
        working-directory: ./10x-cards
        run: npm ci

      - name: Run tests
        working-directory: ./10x-cards
        run: npm run test:coverage

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 10x-cards

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 10x-cards/.nvmrc
          cache: 'npm'
          cache-dependency-path: 10x-cards/package-lock.json

      - name: Install dependencies
        working-directory: ./10x-cards
        run: npm ci

      - name: Build project
        working-directory: ./10x-cards
        run: npm run build
